<?php if(CONFIG::$debug){ ?>
  <link href="css/extern/bootstrap.css" rel="stylesheet">
  <link href="css/myflow.css" rel="stylesheet">
  <link href="css/main.css" rel="stylesheet">
  <link href="css/style.css" rel="stylesheet">
<?php }else{ ?>
  <link href="css/extern/bootstrap.min.css" rel="stylesheet">
  <link href="css/min.css" rel="stylesheet">
<?php } ?>
